### ISSUE TITLE
deployment pods are left in Terminating state

### ISSUE THREAD

**Issue by davidkarlsen** [kuberhealthy/kuberhealthy#1008]
**Describe the bug**
From time to time there will be pods stuck on terminating:
```
k -n kuberhealthy get pods
NAME                                     READY   STATUS        RESTARTS   AGE
deployment-deployment-7c775dfbdd-6csn5   0/1     Terminating   0          5d17h
```

it's always the deployment one, never the daemonset

**Steps To Reproduce**
- Run kuberhealthy

**Expected behavior**
All test pods should be removed properly

**Screenshots**
N/A

**Versions**
 - OCP 4.7
 - Kubernetes Version: 1.20
 - Kuberhealthy Release or build [e.g. 0.1.5 or 235]

**Additional context**
chart install params:

```
spec:
    chart:
      spec:
        chart: kuberhealthy
        sourceRef:
          kind: HelmRepository
          name: kuberhealthy
          namespace: flux-system
        version: "77"
    interval: 10m
    values:
      imageRegistry: docker-nexus.finods.com/kuberhealthy
      podDisruptionBudget:
        enabled: false
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
      resources:
        requests:
          cpu: 10m
```
