### ISSUE TITLE
pods not deleting after the checks completed

### ISSUE THREAD

**Issue by mohang6770** [kuberhealthy/kuberhealthy#1113]
**Describe the bug**
pods not deleting after the checks completed

kuberhealthy version: 2.70
k8s version 1.23.6

**Comment by SaschaP95** [comment]
Same issue here.

kuberhealthy version 2.7.1
K8s version: 1.25.x

**Comment by Hungrylion2019** [comment]
1. if the pods' nodes  not ready
2. adjust the config 'maxCompletedPodCount', and the reaper will recycle the pods
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kuberhealthy
  namespace: kuberhealthy
data:
  kuberhealthy.yaml: |-
    listenAddress: ":8080" # The port for kuberhealthy to listen on for web requests
    enableForceMaster: false # Set to true to enable local testing, forced master mode
    logLevel: error # Log level to be used (default: debug)
    influxUsername: "" # Username for the InfluxDB instance
    influxPassword: "" # Password for the InfluxDB instance
    influxURL: "" # Address for the InfluxDB instance
    influxDB: "http://localhost:8086" # Name of the InfluxDB database
    enableInflux: false # Set to true to enable metric forwarding to Infux DB
    maxKHJobAge: 15m
    maxCheckPodAge: 72h
    maxCompletedPodCount: 1
    maxErrorPodCount: 1
```
