### ISSUE TITLE
Why is our Kuberhealthy namespace check pulling so many images - when imagePullPolicy: IfNotPresent

### ISSUE THREAD

**Issue by pwyborn** [kuberhealthy/kuberhealthy#1133]
### **Describe the bug**
**We have recently been advised by Docker that we have greatly exceeded our image pull quota.
One of the biggest culprits appears to be Kuberhealthy checks:**

### **Example of the number of pulls we have been advised by Docker**
```
Repo Name                            Pulls per Day

kuberhealthy-namespace-check         42,058
kuberhealthy/deployment-check         2,465
kuberhealthy/dns-resolution-check     7,010
kuberhealthy/daemonset-check.         1,455
```

### **Khchecks**

`kubectl -n kuberhealthy get khcheck`
```
NAME                  AGE
daemonset             335d
deployment            335d
dns-status-internal   335d
namespace-kh-check    83d
```
### **Khstate**
`kubectl -n kuberhealthy get khstate`
```
NAME                  OK     AGE LASTRUN   AGE
daemonset             true   5m26s         335d
deployment            true   4m39s         335d
dns-status-internal   true   1s            335d
namespace-kh-check    true   27s           82d
```

`kubectl -n kuberhealthy describe  khstate  namespace-kh-check`
```
Name:         namespace-kh-check
Namespace:    kuberhealthy
Labels:       <none>
Annotations:  <none>
API Version:  comcast.github.io/v1
Kind:         KuberhealthyState
Metadata:
  Creation Timestamp:  2023-03-09T15:04:27Z
  Generation:          697465
  Managed Fields:
    API Version:  comcast.github.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        .:
        f:AuthoritativePod:
        f:Errors:
        f:LastRun:
        f:Namespace:
        f:Node:
        f:OK:
        f:RunDuration:
        f:uuid:
    Manager:         kuberhealthy
    Operation:       Update
    Time:            2023-03-09T15:04:43Z
  Resource Version:  1036559826
  UID:               xxxx
Spec:
  Authoritative Pod:  kuberhealthy-xxxx
  Errors:
  Last Run:      2023-05-31T09:29:14Z
  Namespace:     kuberhealthy
  Node:          ip-xxx-xx-xxx-xxx.eu-west-2.compute.internal
  OK:            true
  Run Duration:  2.630208068s
  Uuid:          xxxxxxxx
Events:          <none>
```

### **Image Pull Policy**

```
# namespace kuberhealthy check
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: namespace-kh-check
  namespace: kuberhealthy
spec:
  runInterval: 30s # The interval that Kuberhealthy will run your check on
  timeout: 2m # After this much time, Kuberhealthy will kill your check and consider it "failed"
  podSpec: # The exact pod spec that will run.  All normal pod spec is valid here.
    containers:
      - env: [] # Environment variables are optional but a recommended way to configure check behavior
        image:  ministryofjustice/cloud-platform-kuberhealthy-namespace-check:1.1
        imagePullPolicy: IfNotPresent
        name: main
        securityContext:
          runAsUser: 999
    serviceAccountName: namespace-check-sa

```
### **We are using helm chart version:**
```
resource "helm_release" "kuberhealthy" {
  name       = "kuberhealthy"
  namespace  = kubernetes_namespace.kuberhealthy.id
  repository = "https://kuberhealthy.github.io/kuberhealthy/helm-repos/"
  chart      = "kuberhealthy"
  version    = "87"
```

### **Expected behavior**
With a policy of only Pull if not present (and events showing "already present on machine", would not expect to see so many pulls:

`kubectl -n kuberhealthy get events -n  kuberhealthy`

```
30s         Normal    Scheduled   pod/namespace-kh-check-xxxxx   Successfully assigned kuberhealthy/namespace-kh-check-xxxxx to ip-xxx-xx-xxx-xxx.eu-west-2.compute.internal
20s         Normal    Pulled      pod/namespace-kh-check-xxxxx   Container image "kuberhealthy-namespace-check:1.1" already present on machine
20s         Normal    Created     pod/namespace-kh-check-xxxxx   Created container main
18s         Normal    Started     pod/namespace-kh-check-xxxxx   Started container main
```

### **Versions**

- Kubernetes Version: 1.23
- AWS EKS
- Kuberhealthy:
  - repository = "https://kuberhealthy.github.io/kuberhealthy/helm-repos/"
  - chart      = "kuberhealthy"
  - version    = "87"
  - Images on Cluster:
```
   6 docker.io/kuberhealthy/daemonset-check:v3.3.0
   7 docker.io/kuberhealthy/deployment-check:v1.9.0
   4 docker.io/kuberhealthy/dns-resolution-check:v1.5.0
   2 docker.io/kuberhealthy/kuberhealthy:v2.7.1
   9 ministryofjustice/cloud-platform-kuberhealthy-namespace-check:1.1
```

### **Additional context**

- Although I cannot see any release notes addressing this issue - 
- Would a later chart address this? Is there an override that we should set - to override anything coming from the chart?
- Has this behaviour been observed before?
