### ISSUE TITLE
multiple URLs in one http-check pod

### ISSUE THREAD

**Issue by SaschaP95** [kuberhealthy/kuberhealthy#1142]
Hey,

I would like to check mutiple URLs with 1 http-check pod instead of creating for each URL one pod.
Is this possible and I didnt find the config possibility or is this not allowed?

**Comment by SaschaP95** [comment]
I would like to solve the error `Check execution error: XXXXX: timed out waiting for checker pod to report in` with this.
We have a lot of http checks and it works fine until we started arround 20.
They run all at the same time and passes if you check the pod log.
But Kuberhealthy exposes as failed in the metrics and the khstate also shows the error.
I didnt find a config parameter to increase the timeout.


So they are 2 questions
- multiple URLs in one http-check pod
- increasing the timeout for the checker pod

thanks in advise

**Comment by mikeinton** [comment]
@SaschaP95 it doesn't appear that the current http check supports multiple URL's in a single `KuberhealthyCheck`.  For timeouts, ave you tried setting `SECONDS` as per the doc here? - https://github.com/kuberhealthy/kuberhealthy/blob/master/cmd/http-check/README.md

**Comment by SaschaP95** [comment]
@mikeinton we have `SECONDS` configured but this is only how much time to wait between the `COUNTS`. Or I understand it completely wrong.

Our http check looks like this
```
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: XXXX
  namespace: kuberhealthy
spec:
  runInterval: 10m
  timeout: 8m
  podSpec:
    imagePullSecrets:
      - name: docker-token
    containers:
      - name: https
        image: XXXX/http-check:v1.5.0
        imagePullPolicy: IfNotPresent
        env:
          - name: CHECK_URL
            value: "http://XXXX"
          - name: COUNT #### default: "0"
            value: "1"
          - name: SECONDS #### default: "0"
            value: "1"
          - name: PASSING_PERCENT #### default: "100"
            value: "100"
          - name: REQUEST_TYPE #### default: "GET"
            value: "GET"
          #- name: REQUEST_BODY #### default: "{}"
          #  value: '{"name": "morpheus", "job": "leader"}'
          - name: EXPECTED_STATUS_CODE #### default: "200"
            value: "200"
        resources:
          requests:
            cpu: 15m
            memory: 15Mi
          limits:
            cpu: 25m
    restartPolicy: Always
    terminationGracePeriodSeconds: 5
```

We use it to check if the URL is available
