### ISSUE TITLE
serviceaccount reference in the deployment template of Helm is not dynamic

### ISSUE THREAD

**Issue by kevin90n** [kuberhealthy/kuberhealthy#1272]
**Describe the bug**
serviceaccount reference in the Kuberhealthy deployment is not dynamic and this causes issues when we use `nameOverride` flag during installation via Helm.

**Steps To Reproduce**
- Run helm install with `nameOverride` flag provided
```
helm install --set nameOverride=customname 
```
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customname
  namespace: default
  labels:
    app: customname
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customname
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: customname
    spec:
      volumes:
        - name: config-volume
          configMap:
            # Provide the name of the ConfigMap containing the files you want
            # to add to the container
            name: kuberhealthy
      serviceAccountName: kuberhealthy <------------ this should be updated to customname
      automountServiceAccountToken: true
      ....
      ....
```
This will keep the serviceaccount reference in the Kuberhealthy deployment as "kuberhealthy" instead of using the overwritten name.

**Expected behavior**
Serviceaccount reference in the deployment is also updated.
