### ISSUE TITLE
Error in network-connection check

### ISSUE THREAD

**Issue by msaitz** [kuberhealthy/kuberhealthy#1283]
**Describe the bug**
I started having errors when using `network-connection` checks with `CONNECTION_TARGET_UNREACHABLE` defined.

It's quite strange, as I have already one defined in good working order, then I noticed that the same one in other x2 clusters was in bad state. After adding a second check trying to reproduce it I've found that it indeeds gets in the bad state.

This seems to happen so far in the `network-connection` check when using the above mentioned env var, as I'm able to create additional regular network connection checks with no issues.

The error I'm getting is noted in the screenshots. Additional details are:
- the check fails to succeed
- the kuberhealthy pod logs the message: `time="2024-10-14T15:26:15Z" level=error msg="Error parsing run duration:  for metric: kuberhealthy_check{check=\"kuberhealthy/network-connection-zookeeper-2-check\",namespace=\"kuberhealthy\",status=\"0\",error=\"Check execution error: kuberhealthy/network-connection-zookeeper-2-check: timed out waiting for pod to exit\"} error: time: invalid duration \"\""`

Interestingly the diff between a working check and a failing one shows no insight on what could be happening.

**Steps To Reproduce**
Unsure if it can be reproduced it in all cases, but applying a manifest like the below 

```
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  annotations:
    meta.helm.sh/release-name: kuberhealthy
    meta.helm.sh/release-namespace: kuberhealthy
  labels:
    app.kubernetes.io/managed-by: Helm
  name: network-connection-zookeeper-2-check
  namespace: kuberhealthy
spec:
  extraAnnotations:
    ad.datadoghq.com/exclude: "true"
  podSpec:
    containers:
    - env:
      - name: CONNECTION_TARGET
        value: tcp://<endpoint:port>
      - name: CONNECTION_TARGET_UNREACHABLE
        value: "true"
      image: docker.io/kuberhealthy/network-connection-check:v0.2.0
      imagePullPolicy: IfNotPresent
      name: network-connection-zookeeper-2
      resources:
        requests:
          cpu: 10m
          memory: 50Mi
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
    restartPolicy: Never
  runInterval: 10m
  timeout: 1m
```

**Expected behavior**

The failing check should detect that the endpoint is unreachable and report back to kuberhealthy the success status

**Screenshots**

Overview of the checks in place:
<img width="711" alt="Screenshot 2024-10-14 at 16 59 10" src="https://github.com/user-attachments/assets/d108a7db-8cac-4274-8387-c94ae1e72880">

Diff from the manifest of the working and failing check (both in the same cluster)
<img width="716" alt="Screenshot 2024-10-14 at 17 08 19" src="https://github.com/user-attachments/assets/0f55b741-e63e-48a1-a8bf-6315a4b93246">

Error logs from the pod with the failing check
<img width="706" alt="Screenshot 2024-10-14 at 17 23 07" src="https://github.com/user-attachments/assets/ca4e8894-d1d3-4a53-85f6-3b0dbc5a5bf1">

**Versions**
 - Cluster OS: EKS
 - Kubernetes Version: 1.28
 - Kuberhealthy Release or build: v2.7.1

**Additional context**
