### ISSUE TITLE
Question - How to test pod restart

### ISSUE THREAD

**Issue by segeva** [kuberhealthy/kuberhealthy#662]
I installed (in AKS) using the following:
helm repo add kuberhealthy https://comcast.github.io/kuberhealthy/helm-repos
helm search repo kuberhealthy
helm upgrade --install kuberhealthy --namespace kuberhealthy  kuberhealthy/kuberhealthy --version 2.2.0 --create-namespace -f dev-values.yaml

I enabled the pod status and restart checks in my dev-values.yaml and also set MAX_FAILURES_ALLOWED: "2"

Deployed also https://github.com/Comcast/kuberhealthy/blob/master/cmd/pod-restarts-check/badPodRestartTestSpec.yaml to the kuberhealthy namespace.
Deployed also a pod with OOM to the same namespace
The 'bad' pods showing status of 'CrashLoopBackOff'

Checked the the kuberhealthy status page after an hour but no error in the restart check.

Also wonder if we can have multiple restart checks in different namespaces

**Comment by joshulyne** [comment]
@segeva making sure i understand your question -- you've enabled pod-restarts and pod-status khchecks and have tried testing it using the `badPodRestartTestSpec.yaml` and no errors were being reported by the pod-restart and pod-status checks? I would recommend you check the logs of the pod-restarts and pod-status checker pods (that are lying around in completed status) to see if they're accurately identifying these bad pods.

 Yes you can have multiple restart checks in different namespaces!

**Comment by segeva** [comment]
@joshulyne My dev-values relevant section:
----------------------
  podRestarts:
    enabled: true
    runInterval: 1m
    timeout: 2m    
    image:
      repository: kuberhealthy/pod-restarts-check
      tag: v2.1.1
    extraEnvs:
      MAX_FAILURES_ALLOWED: "2"      

  podStatus:
    enabled: true
    runInterval: 1m
    timeout: 3m    
    image:
      repository: kuberhealthy/pod-status-check 
      tag: v1.1.2
----------------------------
The lines with error in get pods shows
-------------------------------------------------
NAME                                              READY   STATUS             RESTARTS   AGE
bad-pod-restarter                                 0/1     CrashLoopBackOff   8          19m
liveness-http                                     0/1     CrashLoopBackOff   11         19m
memory-demo-2                                     0/1     CrashLoopBackOff   8          19m
---------------------------
k logs pod-restarts-1601343827
time="2020-09-29T01:43:53Z" level=info msg="Running Pod Restarts checker"
time="2020-09-29T01:43:53Z" level=info msg="Checking for pod BackOff events for all pods in the namespace: kuberhealthy"
time="2020-09-29T01:43:54Z" level=info msg="Successfully reported failure to Kuberhealthy servers"
time="2020-09-29T01:43:54Z" level=info msg="Done running Pod Restarts check
-----------------------------------------------
k logs pod-status-1601343828
time="2020-09-29T01:43:54Z" level=info msg="skipping checks on pod because it is too young: check-reaper-1601343360-ptxvt"
time="2020-09-29T01:43:54Z" level=info msg="skipping checks on pod because it is too young: check-reaper-1601343540-njvlz"
time="2020-09-29T01:43:54Z" level=info msg="skipping checks on pod because it is too young: check-reaper-1601343720-hvcvm"
2020/09/29 01:43:54 checkClient: DEBUG: Reporting SUCCESS
2020/09/29 01:43:54 checkClient: DEBUG: Sending report with error length of:0
2020/09/29 01:43:54 checkClient: DEBUG: Sending report with ok state of:true
2020/09/29 01:43:54 checkClient: INFO: Using kuberhealthy reporting URL:http://kuberhealthy.kuberhealthy.svc.cluster.local/externalCheckStatus
2020/09/29 01:43:55 checkClient: INFO: Got a good http return status code from kuberhealthy URL:http://kuberhealthy.kuberhealthy.svc.cluster.local/externalCheckStatus
time="2020-09-29T01:43:55Z" level=info msg="Reporting Success, no unhealthy pods found."
--------


Note that some initial logs for status picked up the failed pods but showed the message 'Too young...'

So to run another check in a different namespace all I need is to create the 'khchecks' in the namespace? or I need to 'apply' the 'cmd' yaml e.g. https://github.com/Comcast/kuberhealthy/blob/v2.2.0/cmd/pod-restarts-check/pod-restarts-check.yaml   ?

**Comment by integrii** [comment]
Sounds like we need a quick verification (until we can get a test) to ensure that the pod restarts check works.  @jonnydawg should be able to help.

**Comment by joshulyne** [comment]
@segeva you need to `apply` the yaml again with a different namespace!

**Comment by segeva** [comment]
Added the restart khchecks restart (v2.1.1) with POD_NAMESPACE pointing to another NS (sandbox).

Log as follows:
```
k logs pod-restarts-sandbox-1601430331
time="2020-09-30T01:45:38Z" level=error msg="ERROR: The CHECK_TIMEOUT environment variable has not been set."
time="2020-09-30T01:45:38Z" level=info msg="Running Pod Restarts checker"
time="2020-09-30T01:45:38Z" level=info msg="Checking for pod BackOff events for all pods in the namespace: sandbox"
time="2020-09-30T01:45:40Z" level=info msg="Successfully reported failure to Kuberhealthy servers"
time="2020-09-30T01:45:40Z" level=info msg="Done running Pod Restarts check"
```

Note that I added the env CHECK_TIMEOUT with value 10m to the khchecks restart  yaml but no success there...

**Comment by joshulyne** [comment]
@segeva So what we've done is instead of having the `POD_NAMESPACE` pointed to another NS (sandbox), we actually apply the khcheck in the other NS and keep:
```
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
```
ALSO, make sure you're using the latest version of the khcheck: `kuberhealthy/pod-restarts-check:v2.3.0` and let us know if you're still running into issues!

For us, we have a pod-restarts check running in the `kuberhealthy` ns with the following spec:
```
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: pod-restarts
  namespace: kuberhealthy
spec:
  podSpec:
    containers:
    - env:
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: MAX_FAILURES_ALLOWED
        value: "10"
      image: kuberhealthy/pod-restarts-check:v2.3.0
      imagePullPolicy: IfNotPresent
      name: main
      resources:
        requests:
          cpu: 10m
          memory: 50Mi
    restartPolicy: Never
  runInterval: 5m
  timeout: 10m
```

And then another pod-restarts check running in the kube-system ns:
```
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: pod-restarts
  namespace: kube-system
spec:
  podSpec:
    containers:
    - env:
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: MAX_FAILURES_ALLOWED
        value: "10"
      image: kuberhealthy/pod-restarts-check:v2.3.0
      imagePullPolicy: IfNotPresent
      name: main
      resources:
        requests:
          cpu: 10m
          memory: 50Mi
    restartPolicy: Never
  runInterval: 5m
  timeout: 10m
```
