### ISSUE TITLE
ServiceMonitor should allow specifying custom labels so that prometheus-operator can discover them

### ISSUE THREAD

**Issue by AshutoshNirkhe** [kuberhealthy/kuberhealthy#742]
**Describe the feature you would like and why you want it**
Currently ServiceMonitor template has fixed set of labels and doesn't allow specifying additional labels. If we allow specifying that, then existing prometheus-operator that are configured to discover ServiceMonitors based on some label will work fine. As of now, we have to disable ServiceMonitor template and deploy custom one with the matching label(which our prometheus-operator uses). 

**Additional context**

**additional_labels** should be a map of additional labels, which can be inserted in template ar at runtime.

Something on these lines, 
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: {{ template "kuberhealthy.name" . }}
    prometheus: {{ .Values.prometheus.name }}
    release: {{ .Values.prometheus.release }}
    {{ .Values.prometheus.serviceMonitor.additional_labels }}
  name: {{ template "kuberhealthy.name" . }}
  namespace: {{ .Release.Namespace }}
```
