### ISSUE TITLE
current CRDs aren't valid with the new GA-version of apiextensions.k8s.io/v1

### ISSUE THREAD

**Issue by bavarianbidi** [kuberhealthy/kuberhealthy#778]
**Describe the bug**
Since kubernetes 1.16 the `apiextensions.k8s.io/v1beta1` is deprecated and will be unavailable in 1.22.
Deploying a CRD with `apiextension.k8s.io/v1beta1` via `kubectl` leads to following warning:

```
Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
customresourcedefinition.apiextensions.k8s.io/khjobs.comcast.github.io created
```

**Steps To Reproduce**
- Create a cluster with version `1.19` or `1.20` (`kind create cluster`)
  and run 
  ```
  cat << EOF | kubectl apply -f -
  apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: khstates.comcast.github.io
  spec:
    group: comcast.github.io
    version: v1
    scope: Namespaced
    names:
      plural: khstates
      singular: khstate
      kind: KuberhealthyState
      shortNames:
        - khs
   EOF
  ```

**Expected behavior**
No warning message

**Additional context**

But with some autogenerated CRDs we could use [controller-gen](github.com/kubernetes-sigs/controller-tools/cmd/controller-gen) from Kubebuilder.
Maybe useful to solve https://github.com/Comcast/kuberhealthy/issues/603

following CRD-definition works for now:

```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: khchecks.comcast.github.io
spec:
  group: comcast.github.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-embedded-resource: true
        x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: khchecks
    singular: khcheck
    kind: KuberhealthyCheck
    shortNames:
      - khc
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: khstates.comcast.github.io
spec:
  group: comcast.github.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-embedded-resource: true
        x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: khstates
    singular: khstate
    kind: KuberhealthyState
    shortNames:
      - khs
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: khjobs.comcast.github.io
spec:
  group: comcast.github.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-embedded-resource: true
        x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: khjobs
    singular: khjob
    kind: KuberhealthyJob
    shortNames:
      - khj
```
