### ISSUE TITLE
Kuberhealthy Bad Request on GKE (In-cluster inter-pod SNAT behaviour)

### ISSUE THREAD

**Issue by DannyLyubenov** [kuberhealthy/kuberhealthy#870]
**Describe the bug**
`level=fatal msg="error when reporting to kuberhealthy: bad status code from kuberhealthy status reporting url: [400] 400 Bad Request`.
- Kuberhealthy responding with Bad Request after a successful HTTP check.
- This might be down to GKE using NAT for internal routing.
- Related issue - https://github.com/Comcast/kuberhealthy/issues/866
**Steps To Reproduce**
- Obtain Kuberhealthy yaml manifest:
```wget https://raw.githubusercontent.com/Comcast/kuberhealthy/master/deploy/kuberhealthy.yaml```
- Remove default Kuberhealthy checks from the manifest above (truncated for truncated):
```
---
# Source: kuberhealthy/templates/khcheck-daemonset.yaml
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: daemonset
  namespace: kuberhealthy
spec:
  ...
---
# Source: kuberhealthy/templates/khcheck-deployment.yaml
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: deployment
  namespace: kuberhealthy
spec:
  ...
---
# Source: kuberhealthy/templates/khcheck-dns-internal.yaml
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: dns-status-internal
  namespace: kuberhealthy
spec:
  ...
```
- Add to the aforementioned manifest a permissive `PodSecurityPolicy` and associate it to a `ClusterRole` (a GKE requirement, output truncated):
```
---
# Source: kuberhealthy/templates/clusterrole.yaml
apiVersion: "rbac.authorization.k8s.io/v1"
kind: ClusterRole
metadata:
  name: kuberhealthy
rules:
  ...
  - apiGroups: ['policy']
    resources: ['podsecuritypolicies']
    verbs:     ['use']
    resourceNames:
    - kuberhealthy-psp
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: kuberhealthy-psp
spec:
  privileged: true
  allowPrivilegeEscalation: true
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'
```
- Apply the following manifest to a GKE cluster:  
`kubectl apply -n kuberhealthy -f ./kuberhealthy.yaml`
- Create an HTTP GET `khcheck` check in the same namespace: 
```
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: http
  namespace: kuberhealthy
spec:
  serviceAccountName: kuberhealthy-sa
  runInterval: 2m
  timeout: 6m
  podSpec:
    securityContext:
      runAsUser: 999
    containers:
      - name: http
        image: kuberhealthy/http-check:v1.4.2
        imagePullPolicy: IfNotPresent
        env:
          - name: CHECK_URL
            value: "http://google.com"
          - name: COUNT   
            value: "5"
          - name: SECONDS    
            value: "1"
          - name: PASSING_PERCENT
            value: "80"
          - name: REQUEST_TYPE 
            value: "GET"
          - name: EXPECTED_STATUS_CODE
            value: "200"         
        resources:
          requests:
            cpu: 15m
            memory: 15Mi
          limits:
            cpu: 25m
        restartPolicy: Always
    terminationGracePeriodSeconds: 5
```
- Observed logs from the kuberhealthy check pod:
```
time="2021-03-18T17:21:03Z" level=info msg="Beginning check."
time="2021-03-18T17:21:04Z" level=error msg="Got a 200 with a GET to http://google.com"
time="2021-03-18T17:21:04Z" level=error msg="Got a 200 with a GET to http://google.com"
time="2021-03-18T17:21:05Z" level=error msg="Got a 200 with a GET to http://google.com"
time="2021-03-18T17:21:06Z" level=error msg="Got a 200 with a GET to http://google.com"
time="2021-03-18T17:21:07Z" level=error msg="Got a 200 with a GET to http://google.com"
time="2021-03-18T17:21:08Z" level=info msg="5 checks ran"
time="2021-03-18T17:21:08Z" level=info msg="5 checks passed"
time="2021-03-18T17:21:08Z" level=info msg="0 checks failed"
time="2021-03-18T17:22:08Z" level=fatal msg="error when reporting to kuberhealthy: bad status code from kuberhealthy status reporting url: [400] 400 Bad Request "
```
- Observed logs from kuberhealthy replicaset:
```
ime="2021-03-18T17:08:42Z" level=debug msg="Calculating current master..."
time="2021-03-18T17:08:42Z" level=debug msg="Calculated master as kuberhealthy-6b7f66dbcf-nhckh"
time="2021-03-18T17:08:42Z" level=debug msg="My pod hostname is: kuberhealthy-6b7f66dbcf-rlkvn"
time="2021-03-18T17:08:42Z" level=debug msg="I am NOT master"
time="2021-03-18T17:08:42Z" level=debug msg="master status monitor saw a master event"
time="2021-03-18T17:08:47Z" level=info msg="control: waiting for master changes to settle..."
time="2021-03-18T17:08:48Z" level=debug msg="channel notify limiter reached 10s . Sending output"
time="2021-03-18T17:08:48Z" level=debug msg="channel notify limiter finished going through notifications"
time="2021-03-18T17:08:48Z" level=info msg="control: Witnessed a khcheck resource change..."
time="2021-03-18T17:09:13Z" level=info msg="web: c27bbff8-b35d-4832-bb2e-1b145b98b7f2 Client connected to check report handler from <IP>:<PORT> Go-http-client/1.1"
time="2021-03-18T17:09:13Z" level=info msg="web: c27bbff8-b35d-4832-bb2e-1b145b98b7f2 validating external check status report from: <IP>:<PORT>"
time="2021-03-18T17:09:13Z" level=warning msg="was unable to find calling pod with remote IP  <IP>  while watching for duration. Error: failed to fetch pod with remote ip <IP> - found two or more with same ip"
```
**Expected behavior**
Expected the master to acknowledge the `khcheck` HTTP response result
**Versions**
 - Kubernetes Version: v1.18.12-gke.1210
 - Kuberhealthy Release or build 2.4
**Additional context**
***In-cluster inter-pod SNAT behaviour***
Create two simple applications in different namespaces within the same cluster as a demonstration that the source IP of the Pod had been translated (NAT):
```
kns ns1
kubectl run dest-ip-app --image=mirrorgooglecontainers/echoserver:1.4
kubectl expose pod dest-ip-app --name=clusterip --port=80 --target-port=8080
kns ns2
kubectl run source-ip-app --image=mirrorgooglecontainers/echoserver:1.4
kubectl exec -ti source-ip-app bash
$ curl <service IP of dest-ip-app>
CLIENT VALUES:
client_address=<public IP>
command=GET
real path=/
query=nil
request_version=1.1
request_uri=<service IP of dest-ip-app>:<PORT>
```
