### ISSUE TITLE
Refactor helm chart values

### ISSUE THREAD

**Issue by integrii** [kuberhealthy/kuberhealthy#891]
The current helm chart uses a values system like this:

```
imageRegistry: {}

image:
  registry: kuberhealthy
  repository: kuberhealthy
  tag: v2.4.1
```

Given that the format of images is: `<registry>/<org>/<image>:<tag>`, and also considering that users not pulling from docker.io by default is going to be more common (docker being removed from Kubernetes), we should think about refactoring this to make more sense.

I propose we do this when we create a new helm chart repository.

I propose that we change it to something more flat and universally functional, like this: `image: docker.io/kuberhealthy/kuberhealthy:v2.4.1`

This would mean dropping the `imageRegistry`, `registry`, `repository`, `tag` fields.
