### ISSUE TITLE
Security Context doesn't propagate correctly to Khstorage jobs

### ISSUE THREAD

**Issue by blame19** [kuberhealthy/kuberhealthy#953]
**Describe the bug**
We are deploying ChrisHirsch's kuberhealthy storage checks, using the following values.yaml:

```
  storage:
    enabled: true
    extraEnvs:
      CHECK_STORAGE_IMAGE: dev-artifactory.crt.nuance.com/xinfra-docker-prod/kuberhealthy/bitnami/nginx:1.19
      CHECK_STORAGE_INIT_COMMAND_ARGS: chmod 777 /data/
      CHECK_STORAGE_INIT_IMAGE: dev-artifactory.crt.nuance.com/xinfra-docker-prod/kuberhealthy/bitnami/nginx:1.19
    image:
      repository: kuberhealthy-storage-check
      tag: v0.0.1
    nodeSelector:
      kubernetes.io/os: linux
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 64Mi
    runInterval: 60m
    storageClass:
    - default
    - managed-premium
    - azurefile
    timeout: 20m
....
securityContext:
  allowPrivilegeEscalation: false
  enabled: true
  fsGroup: 999
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 999
```
The Security Context is needed in order for the jobs to read the mount correctly (see related issue https://github.com/ChrisHirsch/kuberhealthy-storage-check/issues/14#). However, this doesn't get propagated correctly across the kuberhealthy's deployments.

The context seems to get to the storage-check pods,
```
 k get po -n synthetic storage-check-default-1621593466 -oyaml | grep Context -A 3

  securityContext:
    fsGroup: 999
    runAsUser: 999
  serviceAccount: storage-khcheck
```
but the pods created by the related job don't have the same config:
```
k get po -n synthetic storage-check-pvc-default-init-job-sndq9 -oyaml | grep Context -A 3

  securityContext: {}
```
Infact:
```
 k -n synthetic get job storage-check-pvc-default-init-job -oyaml | grep Context -A 3

      securityContext: {}
```

**Steps To Reproduce**
- Deploy the storage checks as above.

**Expected behavior**
The job should inherit the same security context defined in the values.yaml.

**Versions**
 - Kubernetes Version: 1.19.9 / 1.18
 - Kuberhealthy Release or build: kuberhealthy-63 

**Additional context**
related issue https://github.com/ChrisHirsch/kuberhealthy-storage-check/issues/14#
