### ISSUE TITLE
why comes this error  "error watching for khjob objects: unknown (get khjobs.comcast.github.io)"

### ISSUE THREAD

**Issue by harryyann** [kuberhealthy/kuberhealthy#967]
this is my yaml

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kuberhealthy
  namespace: test-kuberhealthy
  labels:
    app: kuberhealthy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuberhealthy
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kuberhealthy
    spec:
      volumes:
        - name: config-volume
          configMap:
            # Provide the name of the ConfigMap containing the files you want
            # to add to the container
            name: kuberhealthy
      serviceAccountName: kuberhealthy
      automountServiceAccountToken: true
      containers:
      - image: kuberhealthy/kuberhealthy:v2.5.0
        command: [/app/kuberhealthy]
        ports:
        - containerPort: 8080
          name: http
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
          allowPrivilegeEscalation: false
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 2
          periodSeconds: 4
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 1
        name: kuberhealthy
        volumeMounts:
          - name: config-volume
            mountPath: /etc/config/
        env:
          - name: KH_EXTERNAL_REPORTING_URL
            value: "http://10.93.3.254:8080/externalCheckStatus"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 2
          periodSeconds: 4
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 400m
            memory: 300Mi
          limits:
            cpu: 2
            memory: 1Gi
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
```
